# Generated by Django 4.1.5 on 2023-02-06 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductsCategory",
            fields=[
                ("category_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("createDate", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "products category",
                "verbose_name_plural": "product categories",
                "db_table": "d_productsCategory",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("main_image", models.ImageField(upload_to="productImage")),
                ("price", models.DecimalField(decimal_places=8, max_digits=32)),
                ("property1", models.CharField(max_length=5000)),
                ("property2", models.CharField(max_length=5000)),
                ("property3", models.CharField(max_length=5000)),
                ("property4", models.CharField(max_length=5000)),
                ("property5", models.CharField(max_length=5000)),
                ("property6", models.CharField(max_length=5000)),
                ("sale_number", models.IntegerField()),
                ("sale_amount", models.IntegerField()),
                (
                    "customer_rating",
                    models.IntegerField(
                        choices=[
                            (0, "0"),
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                        ]
                    ),
                ),
                ("review", models.TextField()),
                (
                    "temporary_status",
                    models.IntegerField(choices=[(0, "out-of-stock"), (1, "normal")]),
                ),
                ("photo1", models.ImageField(upload_to="productImage")),
                ("photo2", models.ImageField(upload_to="productImage")),
                ("photo3", models.ImageField(upload_to="productImage")),
                ("photo4", models.ImageField(upload_to="productImage")),
                ("createDate", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="goods.productscategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
                "db_table": "d_product",
            },
        ),
    ]
