# Generated by Django 4.1.5 on 2023-01-18 14:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("market_price", models.DecimalField(decimal_places=8, max_digits=32)),
                ("price", models.DecimalField(decimal_places=8, max_digits=32)),
                ("unit", models.CharField(max_length=10)),
                ("amount", models.IntegerField()),
                ("click_num", models.IntegerField()),
                ("fav_num", models.IntegerField()),
                ("goods_desc", models.TextField(max_length=5000)),
                ("main_image", models.CharField(max_length=5000)),
                ("stock_num", models.IntegerField()),
                ("createDate", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
                "db_table": "d_product",
            },
        ),
        migrations.CreateModel(
            name="ProductsCategory",
            fields=[
                ("category_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("level", models.IntegerField()),
                ("sort", models.IntegerField()),
                ("createDate", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "products category",
                "verbose_name_plural": "product categories",
                "db_table": "d_productsCategory",
            },
        ),
        migrations.CreateModel(
            name="Slide",
            fields=[
                ("slide_id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "images",
                    models.ImageField(upload_to="slide", verbose_name="slide picture"),
                ),
                ("sort", models.IntegerField(default=0)),
                ("create_date", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="goods.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "slide picture",
                "verbose_name_plural": "slide pictures",
                "db_table": "d_slide",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="goods.productscategory",
            ),
        ),
    ]
