# Generated by Django 4.1.5 on 2023-02-04 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "purchase_order_number",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("total_order_amount", models.IntegerField()),
                (
                    "purchase_order_status",
                    models.CharField(
                        choices=[
                            (0, "pending"),
                            (1, "hold"),
                            (2, "shipped"),
                            (3, "cancelled"),
                        ],
                        max_length=1200,
                    ),
                ),
                ("shipped_date", models.DateTimeField()),
                ("cancelDate", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "db_table": "d_order",
            },
        ),
        migrations.CreateModel(
            name="ShoppingCart",
            fields=[
                (
                    "shopping_cart_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("count_number", models.IntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="goods.product",
                    ),
                ),
            ],
            options={"verbose_name": "shopping cart", "db_table": "d_shoppingcart",},
        ),
        migrations.CreateModel(
            name="OrderList",
            fields=[
                (
                    "order_list_number",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("total_price", models.DecimalField(decimal_places=8, max_digits=32)),
                ("total_number", models.IntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="order.order"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="goods.product",
                    ),
                ),
            ],
            options={"verbose_name": "order list", "db_table": "d_order_list",},
        ),
    ]
