# Generated by Django 4.1.5 on 2023-02-11 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShippingAddress",
            fields=[
                ("shipping_id", models.IntegerField(primary_key=True, serialize=False)),
                ("receiver_name", models.CharField(max_length=50)),
                ("receiver_phone", models.IntegerField()),
                ("receiver_mobile", models.IntegerField()),
                ("receiver_province", models.TextField(max_length=100)),
                ("receiver_city", models.CharField(max_length=100)),
                ("receiver_district", models.CharField(max_length=100)),
                ("receiver_address", models.TextField(max_length=100)),
                ("receiver_zip", models.IntegerField()),
                ("create_time", models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                "verbose_name": "product information",
                "verbose_name_plural": "product_information",
                "db_table": "d_shippingAddress",
            },
        ),
    ]
